apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: car-mod-monitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: car-mod  
  namespaceSelector:
    matchNames:
      - default  
  endpoints:
  - port: http  
    path: /metrics