prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: 'flask-app'
        scheme: 'https'  
        static_configs:
          - targets: ['vj.klizos.com:443']
        metrics_path: /metrics